import random

kelompok = [['MOCHAMAD FARHAN MARGA KUSUMA', 'FARHAN HAFIZH', 'MOHAMAD ILHAM DWI FIRMANSYAH'],
['FRANSISCA DIVA AMADEA', 'ANGGA KURNIAWAN', 'ATIKA MARASABESSY'],
['MUHAMMAD NANDA SETIAWAN', 'ARIQOH FAUZIYAH IRBAH', 'INDAH RAHMADHANIA'],
['FERISA TRI PUTRI PRESTASI', 'GALANG REFORMANTOKO', 'RENJIRO OWEN'],
['AHMAD MUHAJIR', 'ALDI EKA WAHYU WIDIANTO', 'YOHANES A CRUX GOSAL'],
['YULIANITA', 'SOMA USHIO', 'MUHAMMAD JEFRI FRANSISKA'],
['RIF`AN AMROZI', 'EDWIN RISBOWO', 'HENGKY KURNIAWAN'],
['ZUHAIR', 'JULINAR', 'RIO TINTO HERLAMBANG'],
['SUMIHAR CHRISTIAN N S', 'ANDI AQIL AMANULHAQ', 'YUDA HENDRIAWAN BUDI HANDOKO','MIRDHA SUCI ANANDA',],
['SOVIA PRABANINGTYAS', 'NUR LAILI ASTI PRAMESTI', 'SHAFIRA HERLINAWATI','ALLIF ALFIYAN']]

for i in range(100):
    random.shuffle(kelompok)

from pprint import pprint
pprint(kelompok)